server:
  port: 9099
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hbook?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useOldAliasMetadataBehavior=true&allowMultiQueries=true
    username: root
    password: 96ZaI69464!
  redis:
    host: 127.0.0.1
    port: 6379
    AUTH: xin1127
    password: xin1127
    database: 0
file:
  localPath: /home/web/hbook/img/
