
spring:
  profiles:
    active: dev #prod 线上 dev 开发
  mvc:
    static-path-pattern=/**:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources,classpath:/resources/,classpath:/static/,classpath:/public/
  servlet: # 配置上传文件大小限制
    multipart:
      max-file-size: 100MB #单个文件大小
      max-request-size: 100MB #总文件大小
  datasource:
    druid:
      min-idle: 5
      max-active: 200
      max-wait: 6000
      timeBetweenEvictionRunsMillis: 60000
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  #type-aliases-package: classpath:com.tzs.hbook.*.entity
  messages:
    encoding: utf-8
  configuration:
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#权限管理
shiro:
  #token 过期时间请正确输入用户名/密码
  tokenTimeOut: 604800000
  #免登录接口
  anonUrl: /login,/loginOut,/event,/state,/state*,/get-greeting,/event/*,/*.jpg,/image/**,/*.txt,/test/**,
           /img/face/event/*,/image,/kafka,/kafka/*,swagger/**,/swagger-ui.html,swagger-ui.html,/webjars/**,
           /swagger-ui.html/*,/swagger-resources,/swagger-resources/***,/v2/**,/swagger-resources/**,
          /csrf,/register/*,/antique-info/index,/api/pie-data

#日志打印级别
logging:
  level:
    com.tzs.hbook.system.dao: debug
#文件保存路径
file:
  urlPath: http://192.168.1.84:9999/img/

mail:
  fromurl: 2876254051@qq.com
  password: ajcptihyfsxbdccb
  smtphost: smtp.qq.com
  smtpport: 587
  smtpauth: true
  starttlsenable: true


